#!/usr/bin/env python3
"""Generate derived render inputs from data/sites/*.yml. Deterministic; no judgment.

Two outputs, both regenerated wholesale and both drift-checked by
scripts/check_integrity.py:

  packs/<id>.md         one page stub per record
  data/packs_index.yml  a flat, sorted LIST of records for the index pages

The index exists because Jekyll exposes data/sites/ as a Hash, which Liquid
cannot sort. Sorting is deterministic work, so it happens here in code rather
than in a template.
"""
import pathlib

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
out = ROOT / "packs"
out.mkdir(exist_ok=True)

records = {p.stem: yaml.safe_load(p.read_text())
           for p in sorted((ROOT / "data" / "sites").glob("*.yml"))}
makers = {m["id"]: m for m in yaml.safe_load((ROOT / "data" / "operators.yml").read_text())}
signals = {p.stem: yaml.safe_load(p.read_text())
           for p in sorted((ROOT / "data" / "signals").glob("*.yml"))}

for stub in out.glob("*.md"):
    if stub.stem not in records:
        stub.unlink()

for rid, rec in records.items():
    title = rec["name"].replace('"', "'")
    (out / f"{rid}.md").write_text(
        "---\n"
        "# GENERATED by scripts/gen-pages.sh from data/sites/ — do not hand-edit.\n"
        "layout: pack-record\n"
        f"pack_id: {rid}\n"
        f'title: "{title}"\n'
        f"permalink: /packs/{rid}/\n"
        "---\n"
    )

# A conflict is two signals sharing (site_id, attribute) and disagreeing on value.
# Derived, never stored: the gnome does not emit a conflict field, and a hand-kept
# one would rot.
by_key: dict = {}
for sig in signals.values():
    if sig.get("site_id"):
        by_key.setdefault((sig["site_id"], sig["attribute"]), []).append(sig)

conflicts_by_pack: dict = {}
for (site_id, attribute), sigs in sorted(by_key.items()):
    if len({str(s["value"]) for s in sigs}) > 1:
        conflicts_by_pack.setdefault(site_id, []).append({
            "attribute": attribute,
            "claims": [{"value": str(s["value"]), "url": s["source_url"],
                        "notes": s.get("notes", "")} for s in sorted(sigs, key=lambda x: x["id"])],
        })

index = []
for rid, rec in sorted(records.items()):
    specs = rec.get("specs", {})
    price = rec.get("price", {})
    conflicts = conflicts_by_pack.get(rid, [])
    index.append({
        "id": rid,
        "name": rec["name"],
        "maker": rec["maker"],
        "maker_name": makers.get(rec["maker"], {}).get("name", rec["maker"]),
        "line": rec.get("line"),
        "status": rec["status"],
        "capacity_l": specs.get("capacity_l"),
        "weight_g": specs.get("weight_g"),
        "price_amount": price.get("amount"),
        "price_currency": price.get("currency"),
        "carry_style": rec.get("carry_style", []),
        "use_case": rec.get("use_case", []),
        "gap_count": len(rec.get("gaps", [])),
        "conflicts": conflicts,
    })

# Records with no published capacity sort last, not first — an unknown is not a zero.
index.sort(key=lambda r: (r["capacity_l"] is None, r["capacity_l"] or 0, r["name"]))

(ROOT / "data" / "packs_index.yml").write_text(
    "# GENERATED by scripts/gen-pages.sh from data/sites/ — do not hand-edit.\n"
    "# A flat, sorted list for the index pages. data/sites/ remains the record of truth.\n"
    + yaml.safe_dump(index, sort_keys=False, allow_unicode=True, width=100)
)

n_conf = sum(len(v) for v in conflicts_by_pack.values())
print(f"gen-pages: {len(records)} stub(s) in packs/, {len(index)} row(s) in data/packs_index.yml, "
      f"{n_conf} derived conflict(s)")
